### ISSUE TITLE
Init caffe model

### ISSUE THREAD

**Issue by shujonnaha** [arslan-chaudhry/dcsp_segmentation#2]
Is the Deeplab model pretrained on MSCOCO dataset?

**Comment by arslan-chaudhry** [comment]
No, it's not. Please consult the README regarding the details of the initialization models.

**Comment by shujonnaha** [comment]
Oh yes, I see. Have you used the regular resnet-100 model pretrained on imagenet or is it the resnet-100 model with atrous convolution? If it is the later, can you please provide me the link of the caffe  resnet model pretrained on imagenet with atrous convolution?

**Comment by arslan-chaudhry** [comment]
I used the former.
